name: geomaks_test
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.2.3
  collection: ^1.17.1
  dio: ^5.6.0
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1

  flutter_svg: ^2.0.9
  freezed_annotation:
  
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  l: ^4.0.2
  loader_overlay: ^3.0.0
  lottie: ^2.7.0
  mask_text_input_formatter: ^2.7.0
  meta: ^1.15.0
  package_info_plus: ^7.0.0
  path: ^1.8.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  platform_info: ^4.0.2
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.1
  pull_to_refresh: ^2.0.0
  pure: ^0.3.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  stream_bloc: ^0.5.3

  modal_bottom_sheet: ^3.0.0
  http: ^0.13.4
  image: ^4.2.0
  internet_connection_checker: ^1.0.0+1
  animated_snack_bar: ^0.4.0
  fluttertoast: ^8.2.8


dependency_overrides:
  http: ^0.13.4


dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  lint: ^2.2.0

flutter_gen:
  output: lib/src/core/gen
  integrations:
    flutter_svg: true
    # flare_flutter: true
    rive: true
    lottie: true

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/png/
    - assets/lottie/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/golos/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/golos/GolosText-SemiBold.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf

